name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Write key to file
      run: |
        echo "${{ secrets.EC2_KEY }}" > /tmp/key.pem
        chmod 400 /tmp/key.pem

    - name: Copy files and build
      run: |
        ssh -i /tmp/key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
          cd /home/ubuntu/app || mkdir -p /home/ubuntu/app && cd /home/ubuntu/app
          git pull origin main
          docker build -t qa2cot .
          docker stop qa2cot || true
          docker rm qa2cot || true
          docker run -d --name qa2cot -p 8000:8000 qa2cot
        "
