name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Write key to file
      run: |
        echo "${{ secrets.EC2_KEY }}" > /tmp/key.pem
        chmod 400 /tmp/key.pem

    - name: Copy files and build
      run: |
        ssh -i /tmp/key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
          # 앱 디렉토리 생성
          mkdir -p /home/ubuntu/app
          cd /home/ubuntu/app
        
          # Docker 설치 여부 확인 후 설치
          if ! command -v docker &> /dev/null; then
            sudo apt update
            sudo apt install -y docker.io
            sudo systemctl enable --now docker
            sudo usermod -aG docker $USER
          fi
        
          # Git repo가 없으면 clone, 있으면 pull
          if [ ! -d .git ]; then
            git clone https://github.com/braveveigar/qa2cot.git .
          else
            git pull origin main
          fi
        
          # Docker build/run
          sudo docker build -t qa2cot .
          sudo docker stop qa2cot || true
          sudo docker rm qa2cot || true
            sudo docker run -d \
              --name qa2cot \
              -p 8000:8000 \
              -e GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} \
              -e LLM_MODEL=${{ secrets.LLM_MODEL }} \
              qa2cot
        "
